### ISSUE TITLE
Make verbose logging configurable per route

### ISSUE THREAD

**Issue by jasonclark1985** [MonsantoCo/ocelot#1]
Kubernetes ingress resources on Google Cloud Platform require that health checks be hooked up to GCP load balancer health checks, constantly pinging an ocelot route to keep the cluster healthy.  It would be helpful to have the ability to configure verbose logging at the route level such that the health check endpoints do not needlessly spam the Ocelot logs.

**Comment by theodorick** [comment]
merged
